name: Validate

on:
  push:
    paths:
      - CITATION.cff
  workflow_dispatch:

jobs:
  validate:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v3
